version: '3'

services:

    postgres:
        image: 'w241-final-project/postgres'
        build:
            context: .
            dockerfile: ./docker/db.dockerfile
        environment: 
            POSTGRES_PASSWORD: CHANGEME
        volumes:
            - db-data:/var/lib/postgresql/data

    rest_api:
        build:
            context: .
            dockerfile: ./docker/rest_api.dockerfile
        image: 'w241-final-project/rest_api'
        ports:
            - 81:5000
        volumes:
            - ./rest_api:/app
        environment: 
            FLASK_ENV: production
        depends_on: 
            - postgres
        links:
            - "postgres"

    frontend:
        build:
            context: .
            dockerfile: ./docker/frontend.dockerfile
        image: 'w241-final-project/frontend'
        ports:
            - 80:5000
        depends_on: 
            - rest_api
        environment:
            NODE_ENV: production
            REST_API_URL: 52.117.215.3:81

volumes:
    db-data:
        driver: local
