version: '3'

services:

    postgres:
        image: 'w241-final-project/postgres'
        build:
            context: .
            dockerfile: ./docker/db.dockerfile
        environment: 
            POSTGRES_PASSWORD: CHANGEME
        volumes:
            - db-data:/var/lib/postgresql/data

    rest_api:
        build:
            context: .
            dockerfile: ./docker/rest_api.dockerfile
        image: 'w241-final-project/rest_api'
        ports:
            - 5000:5000
        volumes:
            - ./rest_api:/app
        environment: 
            FLASK_ENV: development
        depends_on: 
            - postgres
        links:
            - "postgres"

    frontend:
        build:
            context: .
            dockerfile: ./docker/frontend.dockerfile
        image: 'w241-final-project/frontend'
        ports:
            - 5001:5000
        volumes:
            - ./frontend:/app
        depends_on: 
            - rest_api

volumes:
    db-data:
        driver: local
